### ISSUE TITLE
Protocol error (Network.getResponseBody): Target closed.

### ISSUE THREAD

**Issue by beri75** [chrishubert/whatsapp-api#134]
Hi, 
after a session successfully connected  one disconnection from device cause  this error:

**ProtocolError: Protocol error (Network.getResponseBody): Target closed.**

ProtocolError: Protocol error (Network.getResponseBody): Target closed.
    at C:\WorkSpace\NodeArea\whatsapp-api-master\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\WorkSpace\NodeArea\whatsapp-api-master\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
    at C:\WorkSpace\NodeArea\whatsapp-api-master\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPResponse.js:128:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPResponse.text (C:\WorkSpace\NodeArea\whatsapp-api-master\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPResponse.js:148:25)
    at async C:\WorkSpace\NodeArea\whatsapp-api-master\node_modules\whatsapp-web.js\src\Client.js:744:44 {
  originalMessage: ''
}

Further info: Windows OS, Node version: v18.15.0.
Any tips or suggestions should be appreciated....

BTW Thank's for sharing!!!

**Comment by chrishubert** [comment]
I would recommend using the docker version - puppeteer is already configured to run properly there.
