### ISSUE TITLE
Server crashes when disconnecting session

### ISSUE THREAD

**Issue by Ant0nioSouza** [chrishubert/whatsapp-api#160]
At first, I thought it was just my impression, but now it has occurred for the second time. The server crashes SOMETIMES when I disconnect the session through the WhatsApp application on my smartphone.
Why this happens, and how could I fix it?

```sh
Browser page closed for 7eb069dd-e682-43d1-8bd3-e3c90d068aca. Restoring
/home/antonio/Documents/project-x/code/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.getResponseBody): Target closed.
    at /home/antonio/Documents/project-x/code/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/home/antonio/Documents/project-x/code/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at /home/antonio/Documents/project-x/code/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:128:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPResponse.text (/home/antonio/Documents/project-x/code/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:148:25)
    at async /home/antonio/Documents/project-x/code/whatsapp-api/node_modules/whatsapp-web.js/src/Client.js:757:44 {
  originalMessage: ''
}

```

My enviroment:
```
Node version: v20.11.1
OS: Ubuntu 22.04


axios ^1.6.5
dotenv ^16.3.1
express ^4.18.2
express-rate-limit ^6.11.2
qr-image ^3.2.0
qrcode-terminal: ^0.12.0
swagger-ui-express: ^4.6.3
whatsapp-web.js: 1.23.1-alpha.4

```

**Comment by avoylenko** [comment]
Could you remove the **RECOVER_SESSIONS** env and verify if this helps you?

**Comment by Ant0nioSouza** [comment]
> Could you remove the **RECOVER_SESSIONS** env and verify if this helps you?

Okay, this helped with the error, but now my sessions will not be recovered. :/
Why does the error happen? How can I fix it to have my sessions recovered?
