### ISSUE TITLE
Puppeteer expection killing the App

### ISSUE THREAD

**Issue by raffus** [chrishubert/whatsapp-api#165]
When disconnecting the session, the app dies with the following message:

```
/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.getResponseBody): Target closed.
    at /usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at /usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:128:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPResponse.text (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:148:25)
    at async /usr/src/app/node_modules/whatsapp-web.js/src/Client.js:757:44 {
  originalMessage: ''
}
```
This happened using the `container` and also when running through `npm start`.

Thanks for the help and good luck fixing it.

Cheers.

**Comment by avoylenko** [comment]
@raffus a temporary solution is to set the **RECOVER_SESSIONS** env to false. Need more time to find why the exception is not handled.

**Comment by raffus** [comment]
Hi there @avoylenko, thanks for the reply. I'll test and give you a feedback.
Also, is there anyway to avoid the API from retrieving old messages?
HUGE Thanks.
