### ISSUE TITLE
Session dissonects after docker restart

### ISSUE THREAD

**Issue by t0mer** [chrishubert/whatsapp-api#174]
Hi,
I'm using the docker version of your amazing work.
It's been a while since i used it and now, after the first run everything works but when I restart the container is stops working 
and the following error appears in the logs:

```
Server running on port 3000
existing session detected tklein
/usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /usr/src/app/node_modules/whatsapp-web.js/src/Client.js:771:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1
```

I have permissions to the sessions folder and it seems that all files are there and have write permissions.

Thanks

**Comment by gamingflexer** [comment]
Ya same issues here !

**Comment by gamingflexer** [comment]
Yeah, i will ping back if i get any updates.

**Comment by arktnld** [comment]
This is related to this issue [whatsapp-web.js #2789](https://github.com/pedroslopez/whatsapp-web.js/issues/2789)

**Comment by rohankm** [comment]
facing the same issue.. any solution?
