### ISSUE TITLE
exited with code 1 error

### ISSUE THREAD

**Issue by dr400** [chrishubert/whatsapp-api#188]
run docker-compose pull && docker-compose up in the whatsapp directory. All seems to be fine until I connect tio http://localhost:3000/session/start/ABCD where the code 1 error arrives. No QR code and container is stopped.

`whatsapp_web_api exited with code 1
whatsapp_web_api  |
whatsapp_web_api  | > whatsapp-web-api@1.0.0 start
whatsapp_web_api  | > node server.js
whatsapp_web_api  |
whatsapp_web_api  | Server running on port 3000
whatsapp_web_api  | existing session detected ABCD
whatsapp_web_api  | /usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
whatsapp_web_api  |         const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
whatsapp_web_api  |                                                                     ^
whatsapp_web_api  |
whatsapp_web_api  | TypeError: Cannot read properties of null (reading '1')
whatsapp_web_api  |     at LocalWebCache.persist (/usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
whatsapp_web_api  |     at /usr/src/app/node_modules/whatsapp-web.js/src/Client.js:771:36
whatsapp_web_api  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
whatsapp_web_api  |
whatsapp_web_api  | Node.js v20.11.1
whatsapp_web_api exited with code 1`

**Comment by arktnld** [comment]
Try this #190

**Comment by chrishubert** [comment]
Please use the latest docker version 🙏
