### ISSUE TITLE
Cannot send message to Group (invalid wid)

### ISSUE THREAD

**Issue by Justus1805** [chrishubert/whatsapp-api#199]
Hello everyone,
Unfortunately, I am unable to send messages. I receive the following error:

> Error: Evaluation failed: Error: wid error: invalid wid
>     at new Error (<anonymous>:5:31)
>     at h (https://static.whatsapp.net/rsrc.php/v3/yh/r/nzRrvRgzNjX.js?_nc_x=Ij3Wp8lg5Kz:70:191)
>     at new a (https://static.whatsapp.net/rsrc.php/v3im0c4/yj/l/makehaste_jhash/pfRXqobLtzE.js?_nc_x=Ij3Wp8lg5Kz:227:1582)
>     at Object.k [as createWid] (https://static.whatsapp.net/rsrc.php/v3im0c4/yj/l/makehaste_jhash/pfRXqobLtzE.js?_nc_x=Ij3Wp8lg5Kz:231:873)
>     at pptr://__puppeteer_evaluation_script__:2:53
>     at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
>     at async Client.sendMessage (/usr/src/app/node_modules/whatsapp-web.js/src/Client.js:938:28)
>     at async sendMessage (/usr/src/app/src/controllers/clientController.js:82:22)

I have tried several groups, but without success.
The WID looks (for example) like this: 123456789-11223344556677@g.us
I have tried it with "g.us" and without. And with several groups.
Where is the mistake?

Attached is my (test) configuration:

```
      {
      "chatId": "123456789-11223344556677@g.us",
      "contentType": "Buttons",
      "content": {
        "body": "Hello World!",
       "buttons": [
        {
           "body": "button 1"
        }
       ],
        "title": "Hello World!",
        "footer": "Hello World!"
                }
      }
```

Thank you!

**Comment by firmanalams** [comment]
Have you tested with send string message not a button?
