### ISSUE TITLE
Unable to make a reaction

### ISSUE THREAD

**Issue by Dima-Kal** [chrishubert/whatsapp-api#301]
Hi, i am trying to react to a message but met with the following error:

```
> curl -X 'POST' \
  'https://*******.com/message/react/abcd' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "chatId": "*******@c.us",
  "messageId": "3AD*******733"
}'
{"success":false,"error":"Evaluation failed: TypeError: Cannot read properties of undefined (reading 'replace')\n    at D (https://static.whatsapp.net/rsrc.php/v3ix4k4/yR/l/rt/6dQ7V_oMNaU.js:1193:1521)\n    at a.normalizeEmoji (https://static.whatsapp.net/rsrc.php/v3ix4k4/yR/l/rt/6dQ7V_oMNaU.js:1193:2970)\n    at a.normalizeEmojiFromString (https://static.whatsapp.net/rsrc.php/v3ix4k4/yR/l/rt/6dQ7V_oMNaU.js:1193:2917)\n    at b.getNormalizedOrTofu (https://static.whatsapp.net/rsrc.php/v3ix4k4/yR/l/rt/6dQ7V_oMNaU.js:1193:9191)\n    at b.getEmojiAggregate (https://static.whatsapp.net/rsrc.php/v3ix4k4/yR/l/rt/6dQ7V_oMNaU.js:1193:9067)\n    at Object.x [as updateRecentReaction] (https://static.whatsapp.net/rsrc.php/v3irFx4/yk/l/rt/ZPMclq8zgGr.js:1798:5828)\n    at https://static.whatsapp.net/rsrc.php/v3irFx4/yk/l/rt/ZPMclq8zgGr.js:1809:3459\n    at Generator.next (<anonymous>)\n    at h (https://static.whatsapp.net/rsrc.php/v3/yw/r/qIj0VlbnMIz.js:16:125)\n    at g (https://static.whatsapp.net/rsrc.php/v3/yw/r/qIj0VlbnMIz.js:16:349)"}%
```

the server is working, when tried to send message was successful:
> curl -X 'POST' \
  'https://*****.com/client/sendMessage/abcd' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "chatId": "****@c.us",
  "contentType": "string",
  "content": "Hello World!"
}'

**Comment by Dima-Kal** [comment]
> The `reaction` property is missing in your request body.

What is the property?
I don't see it in the swagger docs
![image](https://github.com/user-attachments/assets/ef0a5cb2-e666-4aa9-9c76-640b8e07cc6e)

**Comment by avoylenko** [comment]
Yeah, i see the problem. Please add the `reaction` property like this:
```
{
  "chatId": "*******@c.us",
  "messageId": "3AD*******733"
   "reaction" : "👍"
} 
```

**Comment by Dima-Kal** [comment]
> Yeah, i see the problem. Please add the `reaction` property like this:
> 
> ```
> {
>   "chatId": "*******@c.us",
>   "messageId": "3AD*******733"
>   "reaction" : "👍"
> } 
> ```

Worked!
Thank you!
