### ISSUE TITLE
Impossible to get session

### ISSUE THREAD

**Issue by lascimmia** [chrishubert/whatsapp-api#35]
Today starting the server:

```
> whatsapp-web-api@1.0.0 start c:\node\WAppAPI\whatsapp-api
> node server.js

Server running on port 8800
existing session detected session
Failed to send new message webhook: session loading_screen Request failed with status code 404 { percent: 0, message: 'WhatsApp' }
Failed to send new message webhook: session loading_screen Request failed with status code 404 { percent: 100, message: 'WhatsApp' }
Failed to send new message webhook: session authenticated Request failed with status code 404 undefined
Failed to send new message webhook: session ready Request failed with status code 404 undefined
```

After a while, it start receiving (very old) messages, but it's impossible to send one, with error:

```
Session state: session CONNECTED
TypeError: data.id.id.substring is not a function
    at Message._patch (c:\node\WAppAPI\whatsapp-api\node_modules\whatsapp-web.js\src\structures\Message.js:91:75)
    at new Message (c:\node\WAppAPI\whatsapp-api\node_modules\whatsapp-web.js\src\structures\Message.js:18:24)
    at Client.sendMessage (c:\node\WAppAPI\whatsapp-api\node_modules\whatsapp-web.js\src\Client.js:699:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendMessage (c:\node\WAppAPI\whatsapp-api\src\controllers\clientController.js:29:22)
```

It was working until yesterday.

**Comment by lascimmia** [comment]
If I try to start again the session, deleting the previous one:
```
> whatsapp-web-api@1.0.0 start c:\node\WAppAPI\whatsapp-api
> node server.js

Server running on port 8800
Failed to send new message webhook: farmacia qr Request failed with status code 404 {
  qr: '2@ZuQc/a6CIPOEKr1qYMtkZbkC8pULyyQpMrvvw96/pxX16EKu7z2l3TgjAFYxJD6Kx/XKhOx9Fk7T1Q==,X3aVfLO5hBlSjtO0CeBD1iM9OmgpZIcdm4QZx8EhSyU=,eLGPPDnzohCVGU3hhYVTsbnfbvM31RBN+sKJ7P1N1Fk=,3Xz9tEUyO6mzfXAWMTkFKNrJEjGeDwIQpyU/c/IZpR0='
}
```

**Comment by chrishubert** [comment]
1. "session loading_screen Request failed with status code 404" This one is the response from your webhook endpoint `BASE_WEBHOOK_URL` you configure in `.env` or `docker-compose` please double check it.
2. Can you please provide more details with the content of the request body you send to the `{{baseUrl}}/client/sendMessage/:sessionId` endpoint?
I have no issue with the basic string:
```
{
  "chatId": "62xxxxxxx@c.us",
  "contentType": "string",
  "content": "Test"
}
```

**Comment by lascimmia** [comment]
It started to work again today.
By the way, my webhook endpoint is `localhost`

**Comment by chrishubert** [comment]
@lascimmia that's strange, let me know if that happens again.
Your end point should be able to receive valid http `POST` requests. 
The default BASE_WEBHOOK_URL, `http://localhost:3000/localCallbackExample` is configured to accept by default all callbacks from the application.
